logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.10.3.28:5432/stest
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
stock:
  selenium:
    driver: http://10.10.3.28:4444/wd/hub/